apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bms-ingress
  namespace: bms-ops
  labels:
    app.kubernetes.io/part-of: bms-operations
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bms.maf.local
      secretName: maf-wildcard-tls
  rules:
    - host: bms.maf.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bms-api
                port:
                  number: 8000
